# Generated by Django 5.2.8 on 2025-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=500)),
                ('username', models.CharField(default='name', max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('permission', models.CharField(choices=[('dashboard', 'Dashboard'), ('pending_jobs', 'Pending Jobs'), ('pending_properties', 'Pending Properties'), ('messages', 'Messages'), ('reports', 'Reports')], max_length=50)),
                ('description', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='admin_media/')),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
